using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PhotoForum.Models
{
    public class Admin : BaseUser
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)] // Specify that Id is not generated by the database
        public override int Id { get; set; }
        public string? PhoneNumber { get; set; }
    }
}
